Kurier5/Controllers/SummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kurier5.Models;
using Kurier5.ViewModels;

namespace Kurier5.Controllers
{
    public class SummaryController : Controller
    {
        public readonly PostAppDatabaseEntities postAppDatabaseEntities = new PostAppDatabaseEntities();

        // GET: Summary
        [HttpGet]
        public ActionResult Index()
        {
            var sender = postAppDatabaseEntities.Senders;
            var reciver = postAppDatabaseEntities.Recivers;

            var SummaryVM = new SummaryVM
            {
                Senders = sender,
                Recivers = reciver,

            };

            return View(SummaryVM);
        }

        [HttpGet]
        public ActionResult EditSender(int id)
        {
            Sender sender = postAppDatabaseEntities.Senders.Find(id);

            return View(sender);
        }

        [HttpPost]
        public ActionResult EditSender(Sender sender)
        {
            Sender exsistingSender = postAppDatabaseEntities.Senders.Find(sender.IdSender);

            exsistingSender.LastNameSender = sender.LastNameSender;
            exsistingSender.NameSender = sender.NameSender;
            exsistingSender.CitySender = sender.CitySender;
            exsistingSender.AddressSender = sender.AddressSender;
            exsistingSender.PhoneSender = sender.PhoneSender;

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditReciver(int id)
        {
            Reciver reciver = postAppDatabaseEntities.Recivers.Find(id);

            return View(reciver);
        }

        [HttpPost]
        public ActionResult EditReciver(Reciver reciver)
        {
            
            Reciver exsistingSender = postAppDatabaseEntities.Recivers.Find(reciver.IdReciver);

            exsistingSender.AddressReciver = reciver.AddressReciver;
            exsistingSender.CityReciver = reciver.CityReciver;
            exsistingSender.NameReciver = reciver.NameReciver;
            exsistingSender.LastNameReciver = reciver.LastNameReciver;
            exsistingSender.PhoneReciver = reciver.PhoneReciver;

            return RedirectToAction("Index");
        }

    }
}

Kurier5/Views/Summary/EditReciver.cshtml
@model Kurier5.Models.Reciver
@{
    ViewBag.Title = "EditReciver";
}

<div class="row">
    <div class="col-lg-7">
        <h1>Edytuj dane odbiorcy</h1>
        <br />
        @using (Html.BeginForm("EditReciver", "Summary", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(m => m.IdReciver)

            <div class="formula">
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.NameReciver, new { @class = "myTextBox", @placeholder = "Imię" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.LastNameReciver, new { @class = "myTextBox", @placeholder = "Nazwisko" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.CityReciver, new { @class = "myTextBox", @placeholder = "Miasto" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.AddressReciver, new { @class = "myTextBox", @placeholder = "Adres" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.PhoneReciver, new { @class = "myTextBox", @placeholder = "Telefon" })
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Dalej" class="btnStart" />
            </div>
        }


    </div>
    <div class="col-lg-5">

    </div>
</div>

Kurier5/Views/Summary/EditSender.cshtml
@model Kurier5.Models.Sender
@{
    ViewBag.Title = "EditSender";
}

<div class="row">
    <div class="col-lg-7">
        <h1>Edytuj dane nadawcy</h1>
        <br />
        @using (Html.BeginForm("EditSender", "Summary", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(m => m.IdSender)

            <div class="formula">
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.NameSender, new { @class = "myTextBox", @placeholder = "Imię" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.LastNameSender, new { @class = "myTextBox", @placeholder = "Nazwisko" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.CitySender, new { @class = "myTextBox", @placeholder = "Miasto" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.AddressSender, new { @class = "myTextBox", @placeholder = "Adres" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.PhoneSender, new { @class = "myTextBox", @placeholder = "Telefon" })
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Dalej" class="btnStart" />
            </div>
        }


    </div>
    <div class="col-lg-5">

    </div>
</div>

Kurier5/Views/Summary/Index.cshtml
@model Kurier5.ViewModels.SummaryVM

@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div style="width:400px; display:inline-block; float:left;">
        <h1>Czy dane się zgadzają?</h1>
    </div>
    <div>
        <form action="~/Package/NewPack">
            <button type="submit" class="btnStart3">
                tak, dalej &nbsp;
                <i class="fas fa-angle-right">
                </i>
            </button>
        </form>
    </div>
</div>
<div class="row">

    <div class="col-md-3 col-lg-offset-1 myBox">

        <h2>Nadawca:</h2>
        <br />
        <p>Imię i nazwisko: @Model.Senders.Last().NameSender @Model.Senders.Last().LastNameSender</p>
        <p>Adres: @Model.Senders.Last().CitySender, @Model.Senders.Last().AddressSender</p>
        <p>Telefon kontaktowy: +@Model.Senders.Last().PhoneSender</p>
        @Html.ActionLink("Edytuj", "EditSender", "Summary", new { id = Model.Senders.Last().IdSender }, new { @class = "btnStart2" })
    </div>
    <div class="col-md-3 col-lg-offset-1 myBox">

        <h2>Odbiorca:</h2>
        <br />
        <p>Imię i nazwisko: @Model.Recivers.Last().NameReciver @Model.Recivers.Last().LastNameReciver </p>
        <p>Adres: @Model.Recivers.Last().CityReciver, @Model.Recivers.Last().AddressReciver</p>
        <p>Telefon kontaktowy: +@Model.Recivers.Last().PhoneReciver</p>
        @Html.ActionLink("Edytuj", "EditReciver", "Summary", new { id = Model.Recivers.Last().IdReciver }, new { @class = "btnStart2" })
    </div>

</div>