Kurier5/Controllers/PackageController.cs
using System.Web.Mvc;
using Kurier5.Models;

namespace Kurier5.Controllers
{
    public class PackageController : Controller
    {
        public readonly PostAppDatabaseEntities baza = new PostAppDatabaseEntities();
        // GET: Package
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult NewPack()
        {
            Pack package = new Pack();

            return View(package);
        }

        [HttpPost]
        public ActionResult NewPack(Pack package)
        {
            package.Dimensions = package.Height * package.Lenght * package.Width;
            baza.Packs.Add(package);
            baza.SaveChanges();

            return RedirectToAction("Final", "Final");
        }
      
    }
}

Kurier5/Views/Package/NewPack.cshtml
@model Kurier5.Models.Pack

@{
    ViewBag.Title = "NewPack";
}

<div class="row">
    <div class="col-lg-6">
        <h1>Wybierz rodzaj przesyłki &nbsp;<i class="far fa-envelope"></i></h1>
        @using (Html.BeginForm("NewPack", "Package", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            var selectedList = new SelectList(
                new List<SelectListItem>
                {
new SelectListItem {Text= "List", Value="List" },
new SelectListItem {Text= "Paczka", Value="Paczka" },
                }, "Value", "Text");
        <div class="formula">
            @Html.DropDownListFor(m => m.Type, selectedList, "Wybierz rodzaj przesyłki", new { @class = "select-css", @name = "", @id = "purpose", @onchange = "ShowHideDiv()"}) @*//onchange wywołuje funkcje JS "ShowHideDiv"*@
            <div> 
                <div id="business">
                    <div class="formula-row">
                        @Html.TextBoxFor(m => m.Height, new { @class = "myTextBoxShort", @placeholder = "Wysokość (cm)" })
                    </div>

                    <div class="formula-row">
                        @Html.TextBoxFor(m => m.Width, new { @class = "myTextBoxShort", @placeholder = "Szerokość (cm)" })
                    </div>

                    <div class="formula-row">
                        @Html.TextBoxFor(m => m.Lenght, new { @class = "myTextBoxShort", @placeholder = "Długość (cm)" })
                    </div>

                    <div class="formula-row">
                        @Html.TextBoxFor(m => m.Weight, new { @class = "myTextBoxShort", @placeholder = "Waga (kg)" })
                    </div>
                  
                    <button type="submit" class="ThreeLinks">Dalej &nbsp;<i class="far fa-paper-plane"></i></button>
                </div>
                <div id="business2" style="margin-top: 40px;"><button style="margin-left:0;"  type="submit" class="ThreeLinks">Dalej &nbsp;<i class="far fa-paper-plane"></i></button></div>
            </div>
            
        </div>
           
        }
    </div>
</div>

<script type="text/javascript">
    function ShowHideDiv() {
        var myDropdown = document.getElementById("purpose");
        var paczkaDiv = document.getElementById("business");
        var listDiv = document.getElementById("business2");
    
        paczkaDiv.style.display = myDropdown.value === "Paczka" ? "block" : "none";
        listDiv.style.display = myDropdown.value === "List" ? "block" : "none";
    }
</script>