Kurier5/Controllers/PostController.cs
using Kurier5.Models;
using System.Web.Mvc;

namespace Kurier5.Controllers
{
    public class PostController : Controller
    {
        public readonly PostAppDatabaseEntities postAppDatabaseEntities = new PostAppDatabaseEntities();
        // GET: Post
       
        public ActionResult Main()
        {
            return View();
        }
       
       
        [HttpGet]
        public ActionResult AddSender()
        {
            Sender sender = new Sender();
            return View(sender);

        }

        [HttpPost]
        public ActionResult AddSender(Sender sender)
        {
            if (!ModelState.IsValid)
            {
                return View("Error");
            }

            postAppDatabaseEntities.Senders.Add(sender);
            postAppDatabaseEntities.SaveChanges();

            return View("AddReciver");
        }

        public ActionResult DeleteSender(int id)
        {
            Sender sender = postAppDatabaseEntities.Senders.Find(id);

            postAppDatabaseEntities.Senders.Remove(sender);
            postAppDatabaseEntities.SaveChanges();

            return RedirectToAction("Index");
        }

       
        [HttpGet]
        public ActionResult AddReciver()
        {
            Reciver reciver = new Reciver();
            return View(reciver);

        }

        [HttpPost]
        public ActionResult AddReciver(Reciver reciver)
        {
            if (!ModelState.IsValid)
            {
                return View("Error");
            }
            
            postAppDatabaseEntities.Recivers.Add(reciver);
            postAppDatabaseEntities.SaveChanges();

            return RedirectToAction("Index","Summary");
        }
        public ActionResult DeleteReciver(int id)
        {
            Reciver reciver = postAppDatabaseEntities.Recivers.Find(id);
            

            postAppDatabaseEntities.Recivers.Remove(reciver);
            postAppDatabaseEntities.SaveChanges();

            return RedirectToAction("Index2");
        }

        [HttpGet]
        public ActionResult EditReciver(int id)
        {
            Reciver reciver = postAppDatabaseEntities.Recivers.Find(id);
            return View(reciver);
        }

        [HttpPost]
        public ActionResult EditReciver(Reciver reciver)
        {
            Reciver exsisingReciver= postAppDatabaseEntities.Recivers.Find(reciver.IdReciver);

            exsisingReciver.NameReciver = reciver.NameReciver;
            exsisingReciver.LastNameReciver = reciver.LastNameReciver;
            exsisingReciver.PhoneReciver = reciver.PhoneReciver;
            exsisingReciver.AddressReciver = reciver.AddressReciver;
            exsisingReciver.CityReciver = reciver.CityReciver;

            return RedirectToAction("Index");
        }
      



    }
}

Kurier5/Views/Post/AddReciver.cshtml
@model Kurier5.Models.Reciver
@{
    ViewBag.Title = "AddReciver";
}


<div class="row">
    <div class="col-lg-7">
        <h1>Dodaj dane odbiorcy</h1>
        <br />
        @using (Html.BeginForm("AddReciver", "Post", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="formula">
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.NameReciver, new { @class = "myTextBox", @placeholder = "Imię" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.LastNameReciver, new { @class = "myTextBox", @placeholder = "Nazwisko" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.CityReciver, new { @class = "myTextBox", @placeholder = "Miasto" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.AddressReciver, new { @class = "myTextBox", @placeholder = "Adres" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.PhoneReciver, new { @class = "myTextBox", @placeholder = "Telefon" })
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btnStart">Dalej &nbsp;<i class="fas fa-angle-right"></i></button>
            </div>
        }


    </div>
    <div class="col-lg-5">

    </div>
</div>

Kurier5/Views/Post/AddSender.cshtml
@model Kurier5.Models.Sender
@{
    ViewBag.Title = "AddSender";
}

<div class="row">
    <div class="col-lg-7">
        <h1>Dodaj dane nadawcy</h1>
        <br />
        @using (Html.BeginForm("AddSender", "Post", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="formula">
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.NameSender, new { @class = "myTextBox", @placeholder = "Imię" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.LastNameSender, new { @class = "myTextBox", @placeholder = "Nazwisko" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.CitySender, new { @class = "myTextBox", @placeholder = "Miasto" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.AddressSender, new { @class = "myTextBox", @placeholder = "Adres" })
                </div>
                <div class="formulaRow">
                    @Html.TextBoxFor(m => m.PhoneSender, new { @class = "myTextBox", @placeholder = "Telefon" })
                </div>
            </div>
            <div>
                <button type="submit" class="btnStart">Dalej &nbsp;<i class="fas fa-angle-right"></i></button>
            </div>
        }


    </div>
    <div class="col-lg-5">

    </div>
</div>

Kurier5/Views/Post/Main.cshtml
@{
    ViewBag.Title = "Main";
}

<div class="row">
    <div class="col-lg-8 ">
        <p class="big">Dostarczymy Twoją paczkę w 24 godziny.</p>
        <h2>
            
            Szanujemy Twój czas, dlatego większość naszych paczek dostarczamy w mniej niż dobę.<br /> Pozostałe jeszcze szybciej.
        </h2>
         @Html.ActionLink("Zaczynamy", "AddSender", "Post", new { @class = "btnStart" })
    </div>
    <div class="col-lg-5">
       
    </div>
</div>